controller_manager:
  ros__parameters:
    update_rate: 1000
    use_sim_time: true

    # 這裡只放「型別」
    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    # 先保留，之後補參數再開
    # imu_sensor_broadcaster:
    #   type: imu_sensor_broadcaster/ImuSensorBroadcaster

    # 各關節控制器：這裡只放「型別」
    FL_hip_controller:      {type: ros2_unitree_legged_control/UnitreeLeggedController}
    FL_thigh_controller:    {type: ros2_unitree_legged_control/UnitreeLeggedController}
    FL_calf_controller:     {type: ros2_unitree_legged_control/UnitreeLeggedController}
    FR_hip_controller:      {type: ros2_unitree_legged_control/UnitreeLeggedController}
    FR_thigh_controller:    {type: ros2_unitree_legged_control/UnitreeLeggedController}
    FR_calf_controller:     {type: ros2_unitree_legged_control/UnitreeLeggedController}
    RL_hip_controller:      {type: ros2_unitree_legged_control/UnitreeLeggedController}
    RL_thigh_controller:    {type: ros2_unitree_legged_control/UnitreeLeggedController}
    RL_calf_controller:     {type: ros2_unitree_legged_control/UnitreeLeggedController}
    RR_hip_controller:      {type: ros2_unitree_legged_control/UnitreeLeggedController}
    RR_thigh_controller:    {type: ros2_unitree_legged_control/UnitreeLeggedController}
    RR_calf_controller:     {type: ros2_unitree_legged_control/UnitreeLeggedController}


joint_state_broadcaster:
  ros__parameters: {}   # 可留空；或另外設定 publish_rate

# 先不要開，除非你有對應的 IMU 介面（Gazebo/硬體）
# imu_sensor_broadcaster:
#   ros__parameters: {}

FL_hip_controller:
  ros__parameters:
    type: ros2_unitree_legged_control/UnitreeLeggedController
    joint_name: FL_hip_joint
    pid: {p: 100.0, i: 0.0, d: 5.0}

FL_thigh_controller:
  ros__parameters:
    type: ros2_unitree_legged_control/UnitreeLeggedController
    joint_name: FL_thigh_joint
    pid: {p: 300.0, i: 0.0, d: 8.0}

FL_calf_controller:
  ros__parameters:
    type: ros2_unitree_legged_control/UnitreeLeggedController
    joint_name: FL_calf_joint
    pid: {p: 300.0, i: 0.0, d: 8.0}

FR_hip_controller:
  ros__parameters:
    type: ros2_unitree_legged_control/UnitreeLeggedController
    joint_name: FR_hip_joint
    pid: {p: 100.0, i: 0.0, d: 5.0}

FR_thigh_controller:
  ros__parameters:
    type: ros2_unitree_legged_control/UnitreeLeggedController
    joint_name: FR_thigh_joint
    pid: {p: 300.0, i: 0.0, d: 8.0}

FR_calf_controller:
  ros__parameters:
    type: ros2_unitree_legged_control/UnitreeLeggedController
    joint_name: FR_calf_joint
    pid: {p: 300.0, i: 0.0, d: 8.0}

RL_hip_controller:
  ros__parameters:
    type: ros2_unitree_legged_control/UnitreeLeggedController
    joint_name: RL_hip_joint
    pid: {p: 100.0, i: 0.0, d: 5.0}

RL_thigh_controller:
  ros__parameters:
    type: ros2_unitree_legged_control/UnitreeLeggedController
    joint_name: RL_thigh_joint
    pid: {p: 300.0, i: 0.0, d: 8.0}

RL_calf_controller:
  ros__parameters:
    type: ros2_unitree_legged_control/UnitreeLeggedController
    joint_name: RL_calf_joint
    pid: {p: 300.0, i: 0.0, d: 8.0}

RR_hip_controller:
  ros__parameters:
    type: ros2_unitree_legged_control/UnitreeLeggedController
    joint_name: RR_hip_joint
    pid: {p: 100.0, i: 0.0, d: 5.0}

RR_thigh_controller:
  ros__parameters:
    type: ros2_unitree_legged_control/UnitreeLeggedController
    joint_name: RR_thigh_joint
    pid: {p: 300.0, i: 0.0, d: 8.0}

RR_calf_controller:
  ros__parameters:
    type: ros2_unitree_legged_control/UnitreeLeggedController
    joint_name: RR_calf_joint
    pid: {p: 300.0, i: 0.0, d: 8.0}
